version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: evault
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build: ./server
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: evault
      DB_SSLMODE: disable
      ENV: development
      PORT: 8080
    volumes:
      - ./server:/app
    working_dir: /app
    command: go run cmd/server/main.go

  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8080
    volumes:
      - ./client:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev

volumes:
  postgres_data: 