version: '3.8'

services:
  postgres-test:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: evault_test
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  evault-server-test:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=test
      - DB_HOST=postgres-test
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=evault_test
      - JWT_SECRET=test-jwt-secret-key
      - GOOGLE_CLIENT_ID=test-google-client-id
      - GOOGLE_CLIENT_SECRET=test-google-client-secret
      - GOOGLE_REDIRECT_URL=http://localhost:3000/auth/callback
    ports:
      - "8081:8080"
    depends_on:
      postgres-test:
        condition: service_healthy
    command: ["./server"]

  evault-client-test:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=test
      - NEXT_PUBLIC_API_URL=http://evault-server-test:8080
    ports:
      - "3001:3000"
    depends_on:
      - evault-server-test

  # Test runner service for integration tests
  integration-tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - NODE_ENV=test
      - API_BASE_URL=http://evault-server-test:8080
    depends_on:
      - evault-server-test
      - postgres-test
    volumes:
      - ./tests:/app/tests
      - ./test-results:/app/test-results
    command: ["npm", "run", "test:integration"]

volumes:
  postgres_test_data: 